import type { Metadata } from "next";
import { Geist, Geist_Mono, Playfair_Display, Playfair } from "next/font/google";
import "./globals.css";
import { WindowProvider } from "@/contexts/window-context";
import { WindowManager } from "@/components/window-manager";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const playfair = Playfair({
  variable: "--font-playfair",
  subsets: ["latin"],
});

const playfairDisplay = Playfair_Display({
  variable: "--font-playfair-display",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${playfairDisplay.variable} ${playfair.variable} antialiased overscroll-contain overflow-hidden`}
      >
        <WindowProvider>
          {children}
          <WindowManager />
        </WindowProvider>
      </body>
    </html>
  );
}
